// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about.vue')['default']
    BxBxlBehance: typeof import('~icons/bx/bxl-behance')['default']
    BxBxlSpotify: typeof import('~icons/bx/bxl-spotify')['default']
    BxBxlTwitter: typeof import('~icons/bx/bxl-twitter')['default']
    BxBxMailSend: typeof import('~icons/bx/bx-mail-send')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonLogoInstagram: typeof import('~icons/carbon/logo-instagram')['default']
    CarbonLogoLinkedin: typeof import('~icons/carbon/logo-linkedin')['default']
    Event: typeof import('./src/components/event.vue')['default']
    Events: typeof import('./src/components/events.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Single: typeof import('./src/components/single.vue')['default']
    SingleEvent: typeof import('./src/components/singleEvent.vue')['default']
    Speakers: typeof import('./src/components/speakers.vue')['default']
  }
}

export { }
