// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('C:/projects/esya-final/src/components/about.vue')['default']
    BxBxlBehance: typeof import('~icons/bx/bxl-behance')['default']
    BxBxlSpotify: typeof import('~icons/bx/bxl-spotify')['default']
    BxBxlTwitter: typeof import('~icons/bx/bxl-twitter')['default']
    BxBxMailSend: typeof import('~icons/bx/bx-mail-send')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonLogoInstagram: typeof import('~icons/carbon/logo-instagram')['default']
    CarbonLogoLinkedin: typeof import('~icons/carbon/logo-linkedin')['default']
    Event: typeof import('C:/projects/esya-final/src/components/Event.vue')['default']
    Footer: typeof import('C:/projects/esya-final/src/components/footer.vue')['default']
    NewEvent: typeof import('C:/projects/esya-final/src/components/NewEvent.vue')['default']
    Single: typeof import('C:/projects/esya-final/src/components/single.vue')['default']
    'Single copy': typeof import('C:/projects/esya-final/src/components/single copy.vue')['default']
    SingleCustom: typeof import('C:/projects/esya-final/src/components/SingleCustom.vue')['default']
    SingleEvent: typeof import('C:/projects/esya-final/src/components/SingleEvent.vue')['default']
    Speakers: typeof import('C:/projects/esya-final/src/components/speakers.vue')['default']
    Sponsors: typeof import('C:/projects/esya-final/src/components/sponsors.vue')['default']
  }
}

export { }
